[project]
name = "simpleenglishrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Parth Mohnot", email = "150487691+parm2006@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "httpx>=0.28.1",
    "optional>=0.0.1",
]

[project.scripts]
simpleenglishrag = "simpleenglishrag:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
